spring.application.name=server
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jackson.deserialization.fail-on-unknown-properties=true
server.servlet.session.timeout=2h
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=false
server.servlet.session.cookie.same-site=lax

openai.api-key=${OPENAI_API_KEY}
openai.model=gpt-5.4-nano